#+TITLE: TODOs
#+Author: Josh Wolfe
#+TODO: TODO UNDERWAY | DONE WAIT

* About
# -*- mode: org; -*-
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="http://www.pirilampo.org/styles/readtheorg/css/htmlize.css"/>
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="readtheorg.css"/>
#+HTML_HEAD: <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
#+HTML_HEAD: <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
#+HTML_HEAD: <script type="text/javascript" src="http://www.pirilampo.org/styles/lib/js/jquery.stickytableheaders.min.js"></script>
#+HTML_HEAD: <script type="text/javascript" src="http://www.pirilampo.org/styles/readtheorg/js/readtheorg.js"></script>

This todo list is mostly for me to keep track of the things I want to do.
It contains ideas I have for packages and tweaks as well as other people's
packages and configs that I should look into.

* Notable configs to look into
  - [[https://github.com/angrybacon/dotemacs][angrybacon/dotemacs]]
    - literate
    - lots of images
    - package explanations
    - exwm
  - [[https://github.com/abo-abo/oremacs][abo-abo/oremacs]]
  - [[https://github.com/wasamasa/dotemacs][wasamasa/dotemacs]]
    - literate
    - evil
    - very well documented
  - [[https://github.com/IvanMalison/dotfiles][IvanMalison/dotfiles]]
    - literate
    - term-mode
    - org export
  - [[https://github.com/joedicastro/dotfiles][joedicastro/dotfiles]]
    - literate
    - images for explanation
    - hydras
    - mu4e

* Things to look into
** TODO Read about emacs =follow-mode=
   Follow mode allows you to extend your scrolling of a buffer across multiple
   splits.

* UNDERWAY Write a package that integrates =org-mode= into projects
  I'm working on this project at [[https://github.com/WolfeCub/org-project/][=org-project=]] on my github if you're interested in contributing.

  The general idea of this package would be to have a org file that integrates
  with either projectile or git projects that can link directly to =TODO:='s in
  code. In addition it should be able remove the TODO from the code once the org
  item has been completed.

* UNDERWAY Write an efficient seam carving application web app
  Seam carving is a technique that can "smart crop" an image i.e. shrinking without
  distorting the image. I think that having a website provides this service would be
  very useful to people.

  - [ ] Write the core seam carving application in C++ as efficiently as possible
  - [ ] Define a protocol for communication between the carver and the web app
  - [ ] Write the web app

* TODO Find a suitable shell setup inside emacs
  Currently I use =urxvt= as an external terminal. Ideally I would like to run
  my shell from within emacs but as of present I haven't found an experience
  smooth enough to use full time. One possibility is using eshell and doing
  all of the configuration in elisp. The other (and more likely option) is using
  =shell=, =term= or =ansi-term= with packages like [[https://github.com/killdash9/better-shell][=better-shell=]].

* TODO Find additional performance tweaks on windows
  Currently I use windows at work and have found that some things don't perform as
  quickly as they do on linux. A few things that require more investigation are:
  - =UTF-8= font display drastically slows down emacs
  - =Magit= is quite slow though this is probably caused by =git= slowness
* TODO Write an app that suggests Github repos based on stars
  The basic idea is an app that would cross reference all of the repos starred by 
  users who also starred the same repos as you and display the most common overlap. 
  This is *very* performance intensive so a better solution or optimizations will
  need to be considered.
