#! /bin/sh

sxhkd &

# Auto Start
xrandr --output eDP1 --mode 1920x1080
xinput set-button-map 14 1 2 3 5 4 6 7 8 9 10 11 12
setxkbmap -option 'caps:ctrl_modifier'
xcape -e 'Caps_Lock=Escape'
dropbox start&
feh --bg-scale ~/Pictures/japan-tokyo-city-wallpaper-2560x1440.jpg

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           9

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

panel &
