#!/bin/sh

bspc config border_width              2
bspc config window_gap                0
bspc config top_padding               0
bspc config split_ratio               0.5
bspc config borderless_monocle        true
bspc config gapless_monocle           true
bspc config focus_follows_pointer     true
bspc config single_monocle            true
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors  true

bspc rule -a Emacs state=tiled

bspc monitor -d I II III IV V VI VII VIII IX X
